# workflow_config.yaml
# Global paths for the workflow. Edit these to match your environment.

fastframe_repo: /afs/cern.ch/user/c/ceimthur/sm4tops-fastframe
fastframe_config: /afs/cern.ch/user/c/ceimthur/sm4tops-fastframe/SM4topsConfigs/Run3_config_DNN.yml
custom_class: /afs/cern.ch/user/c/ceimthur/sm4tops-fastframe/SM4topsSSML

# Where ntuples should be stored (EOS recommended)
# Example: /eos/user/c/ceimthur/ntuples/Run3_config_DNN
ntuples_eos_dir: /eos/user/c/ceimthur/MVA_training_tutorial/baseline_first_try/ntuples

samples:
  - tttt
  - ttt
  - ttW
  - ttZ
  - ttH
  - SingleTop
  - Diboson
  - ttVV
  - Other
  - fake_inclusive
