# ==============================
# USER / ENVIRONMENT
# ==============================
user: ceimthur

afs_root: /afs/cern.ch/user/c/ceimthur
eos_root: /eos/user/c/ceimthur

# ==============================
# PROJECT STRUCTURE
# ==============================
project_name: MVA_training_tutorial
analysis_tag: baseline_first_try

# ==============================
# REPOSITORIES (relative to AFS)
# ==============================
repos:
  fastframe: sm4tops-fastframe
  umami: umami-preprocessing
  dumper: dumper-to-salt

# ==============================
# FASTFRAME
# ==============================
fastframe:
  config: SM4topsConfigs/Run3_config_DNN.yml
  custom_class: SM4topsSSML

# ==============================
# SAMPLES
# ==============================
samples:
  - ttZ
  - tttt
  - ttW
  - ttH
  - SingleTop
  - Diboson
  - ttVV
  - Other
  - fake_inclusive

# ==============================
# UMAMI PREPROCESSING
# ==============================
folds:
  - fold0
  - fold1
  - fold2
  - fold3

preprocessing_config_subdir: upp/configs/SM4top_Run3